/**
 * Generated App Configuration
 *
 * ⚠️ This file is auto-generated by scripts/generate-app-config.js
 * Do not edit manually - changes will be overwritten on next build
 *
 * To change the app mode, run:
 * node scripts/generate-app-config.js [service|employee|all]
 */

export const APP_MODE = 'employee' as const;
